### ISSUE TITLE
malformed dice string error

### ISSUE THREAD

**Issue by F3nr1s** [sstrickl/rolldice#21] opened 2016-03-09 20:19 UTC
Hi,

I have installed the Version 1.15 on my system. If I try
rolldice 1d
I get following message:
rolldice: Problems with the malformed dice string (in number of dice faces), so quitting!
and then it rolls 1d6, how I thought it will do (and how the manpage told me, it would do).

Not a real problem, rather a not really "nice behaviour" of the program.

**Comment by sstrickl** [comment] 2016-03-18 23:05
Thanks!  Turns out this is a duplicate of #20, and I'm about to pull in a request that includes the fix.

**Closed by sstrickl** 2016-03-18 23:05 UTC
Labels: duplicate
